# Tensors
- Tensors are similar to NumPy’s ndarrays, with the addition being that Tensors can also be used on a GPU to accelerate computing.
- An uninitialized matrix is declared, but does not contain definite known values before it is used. When an uninitialized matrix is created, whatever values were in the allocated memory at the time will appear as the initial values.

In [3]:
import torch

x = torch.empty(2, 5)
print(x)

tensor([[0.0000e+00, 0.0000e+00, 7.7052e+31, 1.9447e+31, 5.0207e+28],
        [2.3329e-18, 4.2330e+21, 7.2251e+28, 7.0368e+28, 3.3127e-18]])


In [8]:
x = torch.rand(2, 5)                          # randomly initialized matrix
print(x)

tensor([[0.4473, 0.1796, 0.2222, 0.5205, 0.4941],
        [0.2456, 0.4410, 0.6812, 0.3733, 0.2630]])


In [6]:
x = torch.zeros(2, 5, dtype=torch.long)       # matrix filled zeros and of dtype long
print(x)

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]])


In [9]:
x = torch.tensor([5.5, 3])                    #tensor directly from data
print(x)

tensor([5.5000, 3.0000])


In [11]:
x = x.new_ones(2, 5, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64)
tensor([[-0.2385,  0.5018,  0.2543, -0.4718, -0.0944],
        [ 0.9133,  2.2244, -0.1811, -1.8843,  0.4593]])


In [12]:
print(x.size())                               # torch.Size is in fact a tuple, so it supports all tuple operations

torch.Size([2, 5])


In [13]:
y = torch.rand(2, 5)
print(x + y)
print(torch.add(x, y))

tensor([[-0.1703,  0.7540,  0.8359, -0.0176,  0.6328],
        [ 1.8758,  2.3880,  0.6430, -1.7454,  1.0498]])
tensor([[-0.1703,  0.7540,  0.8359, -0.0176,  0.6328],
        [ 1.8758,  2.3880,  0.6430, -1.7454,  1.0498]])


In [14]:
result = torch.empty(5, 3)                    # providing an output tensor as argument
torch.add(x, y, out=result)
print(result)

tensor([[-0.1703,  0.7540,  0.8359, -0.0176,  0.6328],
        [ 1.8758,  2.3880,  0.6430, -1.7454,  1.0498]])


In [15]:
y.add_(x)                                     # Any operation that mutates a tensor in-place is post-fixed with an _
print(y)                                      # x.copy_() and x.t_()

tensor([[-0.1703,  0.7540,  0.8359, -0.0176,  0.6328],
        [ 1.8758,  2.3880,  0.6430, -1.7454,  1.0498]])


In [16]:
x = torch.randn(4, 4)                         # If you want to resize/reshape tensor, you can use torch.view                     
y = x.view(16)
z = x.view(-1, 8)                             # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


**Read later:**
100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc., are described [here](https://pytorch.org/docs/torch).


In [21]:
a = x.numpy()                                 # converting to numpy array
print(a)                                      # remember x and a are pointing ot the same memory location
                                              # so change in one is reflected in another

[-1.6911159]


In [23]:
b = torch.from_numpy(a)                       # coverting numpy to tensor

In [24]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")             # a CUDA device object
    y = torch.ones_like(x, device=device)     # directly create a tensor on GPU
    x = x.to(device)                          # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))          # ``.to`` can also change dtype together!

**Reference** : https://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html